### ISSUE TITLE
my five blog | Donaldhan Blog

### ISSUE THREAD

**Issue by Donaldhan** [Donaldhan/Donaldhan.github.io#3]
https://donaldhan.github.io/life/2017/11/03/my-five-blog.html 

 my five five write by markdown, power by jekyll in github page

**Comment by Donaldhan** [comment]
how to do this comments

**Comment by imzhi** [comment]
# dsfg

**Comment by Donaldhan** [comment]
@imzhi  hello guys, you are first man to eat Crab。
